export const germanTeamNames = {
  Algeria: "Algerien",
  Argentina: "Argentinien",
  Australia: "Australien",
  Austria: "Österreich",
  Belgium: "Belgien",
  "Bosnia & Herzegovina": "Bosnien und Herzegowina",
  Brazil: "Brasilien",
  Canada: "Kanada",
  "Cape Verde": "Kap Verde",
  Colombia: "Kolumbien",
  Croatia: "Kroatien",
  Curaçao: "Curaçao",
  Czechia: "Tschechien",
  "DR Congo": "DR Kongo",
  Ecuador: "Ecuador",
  Egypt: "Ägypten",
  England: "England",
  France: "Frankreich",
  Germany: "Deutschland",
  Ghana: "Ghana",
  Haiti: "Haiti",
  Iran: "IR Iran",
  Iraq: "Irak",
  "Ivory Coast": "Elfenbeinküste",
  Japan: "Japan",
  Jordan: "Jordanien",
  Mexico: "Mexiko",
  Morocco: "Marokko",
  Netherlands: "Niederlande",
  "New Zealand": "Neuseeland",
  Norway: "Norwegen",
  Panama: "Panama",
  Paraguay: "Paraguay",
  Portugal: "Portugal",
  Qatar: "Katar",
  "Saudi Arabia": "Saudi-Arabien",
  Scotland: "Schottland",
  Senegal: "Senegal",
  Serbia: "Serbien",
  "South Africa": "Südafrika",
  "South Korea": "Republik Korea",
  Spain: "Spanien",
  Sweden: "Schweden",
  Switzerland: "Schweiz",
  Tunisia: "Tunesien",
  Türkiye: "Türkei",
  Uruguay: "Uruguay",
  "United States": "USA",
  Uzbekistan: "Usbekistan",
};

export function displayTeamName(name) {
  return germanTeamNames[name] ?? name;
}
